### ISSUE TITLE
Add documentation to the README.md file.

### ISSUE THREAD

**Issue by troseman** [thinktandem/drupal-contributions#1]
Getting a 404 from https://blog.lando.dev/2020/06/02/lando-drupal-contributions/

**Comment by troseman** [comment]
sorry, just saw on youtube that you're going to post it later. thanks for the tools!

**Comment by serundeputy** [comment]
@troseman fyi published: https://blog.lando.dev/2020/06/30/lando-drupal-contributions/

thanks for checking out these tools!

**Comment by gitressa** [comment]
Thanks @serundeputy, this is a great help! I have added it to the [Running PHPUnit tests](
https://www.drupal.org/docs/testing/phpunit-in-drupal/running-phpunit-tests#s-lando-drupal-contributions) page.

I wonder if the documentation in https://blog.lando.dev/2020/06/30/lando-drupal-contributions/ should get inserted in the project [README.md](https://github.com/thinktandem/drupal-contributions/blob/master/README.md), just in case?

**Comment by serundeputy** [comment]
Thanks @gitressa. 

I agree that there should be some documentation in the README.md. I have not found the time. You up for a PR?

**Comment by gitressa** [comment]
Sure. I think more or less just using the source code from the awesome blog post would work fine, or what do you think? If you agree, I can clean it up (mostly the "Rebuild" part mark-up) and make a PR?

<div class="content__default"><h2 id="why"><a href="#why" aria-hidden="true" class="header-anchor">#</a> Why?</h2> <p>Setting up, testing, and writing Drupal patches can be a confusing gauntlet to the uninitiated. To that end
I've set up the <a href="https://github.com/thinktandem/drupal-contributions" target="_blank" rel="noopener noreferrer">thinktandem/drupal-contributions<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" x="0px" y="0px" viewBox="0 0 100 100" width="15" height="15" class="icon outbound"><path fill="currentColor" d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path> <polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"></polygon></svg></a> repo to automate
as much of the process as possible.</p> <p>The spin ups should be considered completely ephemeral as on every <code>lando rebuild</code> events will be fired to tear down
the current code base and rewrite the database with a fresh install.</p> <p>Using this repo gives you a <code>.lando.yml</code> file configured for Drupal contributions:</p> <ul><li>Automatically grabs the Drupal source code and runs <code>comoposer install</code> on <code>lando rebuild -y</code></li> <li>Automatically kills the source code and database on <code>lando rebuild -y</code> so you can start fresh with each patch</li> <li>Automatically enables <code>simpletest</code></li> <li>Adds a <code>lando test</code> command to invoke Drupal simpletests</li> <li>Adds a <code>lando si</code> command to reinstall the site with fresh DB if you need one (without rebuilding)</li> <li>Adds a <code>lando patch URL</code> command to pull down and apply a patch from drupal.org</li> <li>Adds a <code>lando revert PATCH_NAME</code> command should you need/want to revert a patch</li> <li>Adds a <code>lando create-patch</code> coommand to create a patch from the current branch</li></ul> <h2 id="how"><a href="#how" aria-hidden="true" class="header-anchor">#</a> How?</h2> <p></p> <p>Let's step through how to spin up your contribution workflow. First clone down this repo:</p> <div class="language-bash extra-class"><pre class="language-bash"><code><span class="token function">git</span> clone git@github.com:thinktandem/drupal-contributions.git
<span class="token builtin class-name">cd</span> drupal-contributions
</code></pre></div><p>This gets us the <code>.lando.yml</code> config and scripts to glue all the processes together.</p> <p>Next <code>rebuild</code> the <code>drupal-contributions</code> app:</p> <div class="custom-block tip"><p class="custom-block-title">Rebuild</p> <p>Note that we are using <code>rebuild</code> and not the <code>start</code> command. Rebuild has the events
to trigger getting the Drupal source code and installation.</p></div> <div class="language-bash extra-class"><pre class="language-bash"><code>lando rebuild -y 
</code></pre></div><p>This will pull in the drupal source code from the <code>8.8.x</code> branch, run <code>composer install</code> to get dependencies, install Drupal, enable <code>simpletest</code> module, and provide us with a one time login link (<code>uli</code>).</p> <p>After <code>rebuild</code> completes you should see something similar to this:</p> <div class="language-bash extra-class"><pre class="language-bash"><code>   ___                      __        __        __     __        ______
  / _ <span class="token punctuation">)</span>___  ___  __ _  ___ / /  ___ _/ /_____ _/ /__ _/ /_____ _/ / / /
 / _  / _ <span class="token punctuation">\</span>/ _ <span class="token punctuation">\</span>/  <span class="token string">' \(_-&lt;/ _ \/ _ <span class="token variable"><span class="token variable">`</span>/  '_/ _ <span class="token variable">`</span></span>/ / _ `/  '</span>_/ _ `/_/_/_/ 
/____/<span class="token punctuation">\</span>___/<span class="token punctuation">\</span>___/_/_/_/___/_//_/<span class="token punctuation">\</span>_,_/_/<span class="token punctuation">\</span>_<span class="token punctuation">\</span><span class="token punctuation">\</span>_,_/_/<span class="token punctuation">\</span>_,_/_/<span class="token punctuation">\</span>_<span class="token punctuation">\</span><span class="token punctuation">\</span>_,_<span class="token punctuation">(</span>_<span class="token operator">|</span>_<span class="token operator">|</span>_<span class="token punctuation">)</span>  
                                                                       

Your app has started up correctly.
Here are some vitals:

 NAME            drupal-contributions                           
 LOCATION        /home/gff/code/drupal-ops/drupal-contributions 
 SERVICES        appserver, database                            
 APPSERVER URLS  https://localhost:33147                        
                 http://localhost:33148                         
                 http://drupal-contributions.lndo.site/         
                 https://drupal-contributions.lndo.site/  
</code></pre></div><p>and the <code>web</code> directory should be populated with the Drupal source code.</p> <h2 id="testing-drupal-patches"><a href="#testing-drupal-patches" aria-hidden="true" class="header-anchor">#</a> Testing Drupal Patches</h2> <p>Now we are ready to find a Drupal issue. Search the issue queue for an <code>8.x</code> issue that you want to test. Grab the URL of the latest patch and apply it to our <code>drupal-contributions</code> environment.</p> <p>For example if you choose this issue: https://www.drupal.org/project/drupal/issues/2962649, the latest corresponding patch (as of 25 June 2020) is https://www.drupal.org/files/issues/2019-09-12/2962649-10.patch. To apply this patch:</p> <div class="language-bash extra-class"><pre class="language-bash"><code>lando patch https://www.drupal.org/files/issues/2019-09-12/2962649-10.patch
</code></pre></div><p>To revert the patch:</p> <div class="language-bash extra-class"><pre class="language-bash"><code>lando revert <span class="token number">2962649</span>-10.patch
</code></pre></div><p>This way we can <code>apply</code> and <code>revert</code> as many times as we want/need to during our testing.</p> <p>To test this issue first add a file field to a content type say the page content type at <code>/admin/structure/types/manage/page/fields</code>. Now add a <code>page</code> node at <code>/admin/content/add/page</code> and add a text file to the file field you just made.</p> <p>Visit the page in your web browser and click the file link. The file shows up in the current window. Now apply the patch with:</p> <div class="language-bash extra-class"><pre class="language-bash"><code>lando patch https://www.drupal.org/files/issues/2019-09-12/2962649-10.patch
</code></pre></div><p>and visit the <code>/admin/structure/types/manage/page/display</code> page and click through the gear to get to the settings of the <code>file_link</code> field we added to the <code>page</code> content type. You shoud now see a checkbox for <code>Open file in new tab (target=_blank)</code> which we can check and save.</p> <p>Now visit the page or refresh the page in a web browser and click the file link. This time the file opens in a new tab!</p> <p>The patch works!</p> <p>We can now leave a comment on the issue saying that we tested the patch and it works as expected for us.</p> <h2 id="creating-a-patch"><a href="#creating-a-patch" aria-hidden="true" class="header-anchor">#</a> Creating a Patch</h2> <p>If you are fixing a d.org issue. You shuld checkout a branch using the prescribed naming conventions <code>ISSUE####-COMMENT#.patch</code>. Write your code. Commit your code. Then you can utilize the <code>lando create-patch</code> to output the patch file based on your branch name.</p> <div class="language-bash extra-class"><pre class="language-bash"><code>lando create-patch
</code></pre></div><p>This will output a patch file to <code>/app/web/ISSUE####-COMMENT#.patch</code>, which you can upload to the drupal.org issue.</p> <h2 id="running-tests"><a href="#running-tests" aria-hidden="true" class="header-anchor">#</a> Running Tests</h2> <p>When you create a patch you may have written tests for it that you want to run. At a minimum you'll want to run the tests for the module the patch is for to make sure your changes have not introduced regressions. To run the tests use the <code>lando test</code> command. To see what you can do use:</p> <div class="language-bash extra-class"><pre class="language-bash"><code>lando <span class="token builtin class-name">test</span> --help
</code></pre></div><p>To run the tests from the <code>file</code> module for example use:</p> <div class="language-bash extra-class"><pre class="language-bash"><code>lando <span class="token builtin class-name">test</span> --module <span class="token function">file</span>
</code></pre></div><h2 id="la-fin"><a href="#la-fin" aria-hidden="true" class="header-anchor">#</a> La Fin</h2> <p>Once you have the <code>8.8.x</code> you can keep it and sync it periodically and <code>lando start</code>'s will keep that around. If you want to totally start fresh:</p> <div class="language-bash extra-class"><pre class="language-bash"><code><span class="token comment"># destroys drupal-contributions app and removes /web</span>
lando destroy -y

<span class="token comment"># Spin up a fresh checkout of Drupal source installed and ready</span>
<span class="token comment"># for dev, patching, and testing.</span>
lando rebuild  -y
</code></pre></div><p>I hope you find this useful. If you find bugs, issues, or want addional features drop an issue in <a href="https://github.com/thinktandem/drupal-contributions" target="_blank" rel="noopener noreferrer">thinktandem/drupal-contributions<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" x="0px" y="0px" viewBox="0 0 100 100" width="15" height="15" class="icon outbound"><path fill="currentColor" d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path> <polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"></polygon></svg></a></p></div>

**Comment by serundeputy** [comment]
@gitressa yep. Go for it!

**Comment by gitressa** [comment]
@serundeputy I have created a PR which updates the README: #3. @benjifisher's recent improvements in #2 should probably be added also, but this is a start.

**Comment by serundeputy** [comment]
thanks @gitressa nice improvement!

merged https://github.com/thinktandem/drupal-contributions/pull/3

**Comment by gitressa** [comment]
Awesome, thanks @serundeputy!
