### ISSUE TITLE
Drush 10 and Admin Toolbar?

### ISSUE THREAD

**Issue by gitressa** [thinktandem/drupal-contributions#10]
It looks like Drush version is 8.3.5 ... would it be possible to upgrade this to Drush 10, to get commands like `drush config:status`  and `drush config:export --diff` to work? Also, perhaps adding and enabling `drupal/admin_toolbar` could be considered, to speed things up?

**Comment by serundeputy** [comment]
I'm not up to date on what versions of drush work with what versions of drupal but if we get the 9.x and 10.x branches i'm assuming they will pick up drush 10.

If you want drush 10 with drupal8 i think you can load a site local drush in your composer steps in the .lando.yml file.

**Comment by gitressa** [comment]
Drush 10 works with Drupal 8.4+ (Apr 2018) and Drupal 9: https://www.drush.org/install/#drupal-compatibility
I don't think Drush 9 is of any interest, since it became EOL in May 2020.

Drush 8 is mainly for Drupal 7, and "happens to work" with Drupal 8.

**Comment by serundeputy** [comment]
maybe we should add a site local drush to this project via composer?

**Comment by gitressa** [comment]
I think adding Drush 10 via Composer would make sense.

**Comment by serundeputy** [comment]
up for a PR and we can test it out?

**Comment by gitressa** [comment]
Sure! I have created a PR to add Drush.

**Comment by gitressa** [comment]
Would it make sense to also add `drupal/core-dev` at some point? In that case, we could do it like this in stead, adding this in `scripts/get-drupal.php`:

```
exec(
  "cd web && composer require drupal/core-dev:$drupalBranch drush/drush"
);

```

**Comment by serundeputy** [comment]
Merged in https://github.com/thinktandem/drupal-contributions/pull/12 thanks for that!

I'm not sure about switching to `composer require drupal/core-dev:$drupalBranch` is that a know development pattern for Drupal core? I don't see any reference to it here: https://www.drupal.org/project/drupal/git-instructions

**Comment by gitressa** [comment]
Great, thanks!

I am note sure about `drupal/core-dev` ... perhaps it's not needed, and baked into the https://git.drupalcode.org/project/drupal.git repo? ... the documentation is a bit vague: [Improve documentation and findability for Drupal core development page](https://www.drupal.org/project/drupalorg/issues/3101272). Anyway, it's ready here, if it is ever needed :-)
