### ISSUE TITLE
Is PHPUnit used to run tests?

### ISSUE THREAD

**Issue by gitressa** [thinktandem/drupal-contributions#14]
It says on the [Running PHPUnit tests](https://www.drupal.org/docs/automated-testing/phpunit-in-drupal/running-phpunit-tests) documentation page that:

> PHPUnit runs all the tests in Drupal 8 and above. Earlier versions of Drupal used the Simpletest Module for testing.

When I run PHPUnit in another environment it starts out printing `PHPUnit 7.5.20 by Sebastian Bergmann and contributors.
` at the top, but not here ... so I just want to check if PHPUnit is used to run the tests in Drupal Contributions?

**Comment by serundeputy** [comment]
To run PHPUnit tests run `lando phpunit <blah>`: https://github.com/thinktandem/drupal-contributions/blob/8.x/.lando.yml#L53

To run simpletests run `lando test <blah>`: https://github.com/thinktandem/drupal-contributions/blob/8.x/.lando.yml#L59

**Comment by gitressa** [comment]
Thanks! I got the PHPUnit tests running with this:

Single test
`lando phpunit web/core/modules/big_pipe/tests/src/Functional/BigPipeTest.php`

All tests
`lando phpunit web/core/modules/big_pipe`

I see there are two phpunit.xml files, is that intentional, or can they be consolidated into one file?
https://github.com/thinktandem/drupal-contributions/blob/8.x/phpunit.xml
https://github.com/thinktandem/drupal-contributions/blob/8.x/config/phpunit.xml

**Comment by serundeputy** [comment]
I think one is the one that is used and one is the default `phpunit.xml` file; we can either consolidate or rename on `default.phpunit.xml` probably consolidate is best.

**Comment by gitressa** [comment]
PHPUnit is using `/config/phpunit.xml`, whereas `/phpunit.xml` doesn't seem to be used ... If I run `lando test --file <blah>` it runs fine, even if I delete both of them. So perhaps `/phpunit.xml` can be outright deleted?

**Comment by gitressa** [comment]
Can `/phpunit.xml` be deleted?

**Comment by gitressa** [comment]
Pull request created in #20.

**Comment by gitressa** [comment]
The #20 MR has been merged, which also removed the `/config/phpunit.xml`, file so closing this issue.
