### ISSUE TITLE
PHPUnit parameters

### ISSUE THREAD

**Issue by gitressa** [thinktandem/drupal-contributions#16]
It would be great to be able to use [PHPUnit parameters](https://www.drupal.org/docs/automated-testing/phpunit-in-drupal/running-phpunit-tests#s-run-groups-of-tests) like `--list-groups` and `--group Groupname` to run individual tests, which currently don't seem to work. 

Since updating the paths in `phpunit.xml` might fix this, perhaps this blog post can be an inspiration? [My PHPUnit configuration for my Drupal projects](https://glamanate.com/blog/my-phpunit-configuration-my-drupal-projects).

**Comment by serundeputy** [comment]
I haven't had time to look into this @gitressa :( ... maybe if you could try some of the things in the blog post as they relate to this project and paste your inputs and outputs of your experiments here we can develop a course of action?

thanks for looking into it!

**Comment by gitressa** [comment]
Sure, I'll try to experiment a bit :-) But it would be great to determine in #14 if one of the two `phpunit.xml` files can be removed, to simplify things.

**Comment by serundeputy** [comment]
maybe whilst you experiment remove one or both and see what happens.

**Comment by gitressa** [comment]
I got it working, removing the `/config/phpunit.xml` file, and using the `phpunit.xml` in root, see #20.

```
$ lando phpunit --list-groups
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Available test group(s):
 - #slow
 - Access
 - Action
 - Ajax
 - Annotation
[...]
 - workflows
 - workspace
 - workspaces
 - 44
```

**Comment by serundeputy** [comment]
#20 is merged; thanks @gitressa anything left here or ok to close?

**Comment by gitressa** [comment]
No, I think that's it, thanks! I'll have a look at adding examples to README.md and drupal 9 later.

**Comment by gitressa** [comment]
I have opened a Merge Request which updates PHPUnit for Drupal 9 in #24.

**Comment by serundeputy** [comment]
thanks @gitressa I've merged it into `9.x`

**Comment by gitressa** [comment]
Thanks @serundeputy.
