### ISSUE TITLE
Xdebug

### ISSUE THREAD

**Issue by lukewhitmore** [thinktandem/drupal-contributions#17]
Wondering what the best way to use this with xdebug is?

I've tried enabling xdebug via the config section in the `.lando.yml` file.

It seems that xdebug will fire, but the debugger is trying to interpret 'standard input code'

**Comment by serundeputy** [comment]
yes; `xdebug` should work in the `config` section:

```yaml
config:
  xdebug: true
```

I use it in conjunction w/ Vdebug and works great! Config for your editor might be different. Here is Vdebug: https://github.com/serundeputy/gffNeovim/blob/999b47157749ed9e8502ebba99b6471ad23fab68/gff.init.vim#L182
