### ISSUE TITLE
Flesh out patch creation in detail

### ISSUE THREAD

**Issue by gitressa** [thinktandem/drupal-contributions#22]
I get a lot of content in my patch file, if I try to create a simple patch, containing way too many changes. It would be great if the exact steps to create a patch could be spelled out: https://github.com/thinktandem/drupal-contributions/#creating-a-patch

**Comment by serundeputy** [comment]
thanks @gitressa this video https://youtu.be/vVpKCQZKNtM?t=982 shows how to create a patch; i'd have to look, but I think it is `lando create-patch` command.

If that suits your needs maybe you can file a PR against the README.md that details the steps in the vid, if not we can flesh something out.  For me it is just a matter of finding time for it.

**Comment by gitressa** [comment]
Thanks for the reply @serundeputy, but that bit shows how to apply a patch, not how to create it ... I already tried the `lando create-patch`, but way too many changes are included. Sorry if I weren't too clear about that.

So basically, a list of the minimum required commands to create a patch would be awesome. Perhaps we can try to find them in this issue, and then I can create a PR afterwards?

**Comment by gitressa** [comment]
For example, if I do this:
```
$ git clone git@github.com:thinktandem/drupal-contributions.git
$ cd drupal-contributions
$ lando rebuild -y
$ cd web
```

Checking Git status, it seems like there are changes:
```
$ git status
On branch 8.9.x
Your branch is up to date with 'origin/8.9.x'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  modified:   composer.json
  modified:   composer.lock
  modified:   composer/Metapackage/CoreRecommended/composer.json
  modified:   composer/Metapackage/PinnedDevDependencies/composer.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
  .gitignore

no changes added to commit (use "git add" and/or "git commit -a")
```

Create a branch, update a core file, and create the patch:
```
$ git checkout -b 987654-patch-testing
$ echo "TEST" >> core/CHANGELOG.txt
$ git add core/CHANGELOG.txt
$ git commit -m "Updates CHANGELOG.txt"
$ lando create-patch
```

I would expect a 358 bytes small patch file called `987654-patch-testing.patch`, with this content:
```
diff --git a/core/CHANGELOG.txt b/core/CHANGELOG.txt
index 3b99f6bd5d..3f30a1584c 100644
--- a/core/CHANGELOG.txt
+++ b/core/CHANGELOG.txt
@@ -6,3 +6,4 @@ Drupal release cycle: https://www.drupal.org/core/release-cycle-overview
  https://www.drupal.org/latest-release
 * API change records for Drupal core:
  https://www.drupal.org/list-changes/drupal
+TEST
```

But in stead a 140.8 kB file is created ... which makes sense, since `composer.json`, `composer.lock`, `.gitignore`, etc. were modified. The question is how to avoid them getting included in the resulting patch file?

**Comment by serundeputy** [comment]
thanks @gitressa I understand now.

This function https://github.com/thinktandem/drupal-contributions/blob/8.x/scripts/patch-helpers.php#L69 is trying to do too much. We should remove the `git add -A` part from the `createPatch()` function.

**Comment by gitressa** [comment]
Thanks for looking it over @serundeputy. You're right, removing the `git add -A` line fixes it, and the patch is created correctly. I have created a PR for it: #23.

**Comment by serundeputy** [comment]
Thanks @gitressa !

This is merged into `8.x` and `9.x`.

**Comment by gitressa** [comment]
Cool, thanks @serundeputy!
