### ISSUE TITLE
Should composer be used to download drupal?

### ISSUE THREAD

**Issue by smustgrave** [thinktandem/drupal-contributions#26]
All drupal setups I've done so far I've used composer
composer create-project drupal/recommended-project my_site_name_dir
as a starting point.  I believe this is recommended from what I've read and it moves the vendor folder out of the web folder which is also recommended.  

Thoughts?

**Comment by serundeputy** [comment]
that is a best practice for developing a drupal site, but for this project we need the git tracked drupal source code to make changes, bug fixes, and features and submit them back to the drupal maintainers.

**Comment by smustgrave** [comment]
Gotcha.  Thank you for explaining that to me!
