### ISSUE TITLE
lando destroy doesn't remove /web folder

### ISSUE THREAD

**Issue by gitressa** [thinktandem/drupal-contributions#29]
Previously, I could run `lando destroy`, `cd` up one level and delete the folder with `rm drupal-contributions/ -rf`, but it doesn't currently work:

```
$ lando destroy
[...]
$ cd ..
$ rm drupal-contributions/ -rf
rm: cannot remove 'drupal-contributions/web/sites/default/default.services.yml': Permission denied
rm: cannot remove 'drupal-contributions/web/sites/default/settings.php': Permission denied
rm: cannot remove 'drupal-contributions/web/sites/default/files': Permission denied
```

**Comment by serundeputy** [comment]
yeah; that is the weird permissions drupal has committed to the the files you have listed ... :shrug: 

so you'd need `sudo rm drupal-contributions/ -rf`  .... i don't know why they/drupal puts the weird permissions on those files.

**Comment by gitressa** [comment]
I would assume it's a question of hardening those important files? From a security perspective I guess it make sense :-) I have created a PR, which allows `lando destroy` to remove the web folder: #30.

**Comment by serundeputy** [comment]
Thanks @gitressa I've merged your pr

**Comment by gitressa** [comment]
Great, thanks @serundeputy!
