### ISSUE TITLE
Remove SimpleTest for Drupal 9?

### ISSUE THREAD

**Issue by gitressa** [thinktandem/drupal-contributions#32]
From the [Status page](https://drupal-contributions.lndo.site/admin/reports/status) of a Drupal 9 installation:

> SimpleTest has been removed from Drupal 9.0.0 and can no longer be installed. A contributed module is available for those who wish to continue using SimpleTest during the transition from Drupal 8 to 9. <a href="https://www.drupal.org/node/3091784">See the change record for more information</a>.

**Remanining tasks**
Remove SimpleTest related code in Drupal 9 branch:
https://github.com/thinktandem/drupal-contributions/search?q=SimpleTest

**Comment by serundeputy** [comment]
seems like a good idea to me at least in the `9.x` branch

**Comment by gitressa** [comment]
I have created #44.

**Comment by gitressa** [comment]
The MR has been merged.
