### ISSUE TITLE
Does pre-rebuild execute

### ISSUE THREAD

**Issue by lokapujya** [thinktandem/drupal-contributions#39]
I wonder if pre-rebuild works. After doing a lando rebuild -y
pre-rebuild never executed and I am still not pulling from git.drupalcode.org.
~/Sites/d9 % git remote -v
origin	https://github.com/thinktandem/drupal-contributions.git (fetch)
origin	https://github.com/thinktandem/drupal-contributions.git (push)
If get-drupal.php executed, we would have the full Drupal repo with all branches. I guess this still works for creating patches in HEAD which is 95% of patches.

I'm new to Lando. So, I could have just missed something.

**Comment by serundeputy** [comment]
@lokapujya it works for me.

After you do a `lando rebuild -y` you should have the drupal source code in the `web` directory.

**Comment by lokapujya** [comment]
can you confirm that the origin is git.drupalcode.org and not thinktandem?

**Comment by serundeputy** [comment]
```bash
(base) gff ~/code/drupal-ops/drupal-contributions 
(9.x) └─ ∴ pwd
/home/gff/code/drupal-ops/drupal-contributions
(base) gff ~/code/drupal-ops/drupal-contributions 
(9.x) └─ ∴ git remote -v
origin	git@github.com:thinktandem/drupal-contributions.git (fetch)
origin	git@github.com:thinktandem/drupal-contributions.git (push)
(base) gff ~/code/drupal-ops/drupal-contributions 
(9.x) └─ ∴ cd web/
(base) gff ~/code/drupal-ops/drupal-contributions/web 
(9.2.x) └─ ∴ pwd
/home/gff/code/drupal-ops/drupal-contributions/web
(base) gff ~/code/drupal-ops/drupal-contributions/web 
(9.2.x) └─ ∴ git remote -v
origin	https://git.drupalcode.org/project/drupal.git (fetch)
origin	https://git.drupalcode.org/project/drupal.git (push)
(base) gff ~/code/drupal-ops/drupal-contributions/web 
(9.2.x) └─ ∴ 
```

The git remote of the `app` is thinktandem (this repo). If you `cd web` the remote of that is git.drupalcode.org/project/drupal.git.

**Comment by lokapujya** [comment]
I was checking the repo from the wrong directory.
