### ISSUE TITLE
cross-env: not found

### ISSUE THREAD

**Issue by smustgrave** [thinktandem/drupal-contributions#47]
First off thank you for such a tool! It really has helped me as a developer

I'm currently trying to run some drupal core tests using the nightwatch tool but keep getting 

$ cross-env BABEL_ENV=development node -r dotenv-safe/config -r @babel/register ./node_modules/.bin/nightwatch --config ./tests/Drupal/Nightwatch/nightwatch.conf.js --tag core
/bin/sh: 1: cross-env: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Here is my lando file.  I have had to make some tweaks to it but I left the nightwatch stuff alone

`name: drupal-contributions-drupal9.2
recipe: drupal9
config:
  webroot: web
  xdebug: "debug,develop"
  config:
    php: ./lando-src/php.ini

services:
  appserver:
    build_as_root:
      # Note that you will want to use the script for the major version of node you want to install
      # See: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - npm install --global yarn
#    run:
#      # @todo remove invocation of drupal-phpunit-upgrade again once https://www.drupal.org/project/drupal/issues/3099061 is resolved.
#      - cd /app && composer require drush/drush && composer install && composer run-script drupal-phpunit-upgrade
    overrides:
      environment:
        SIMPLETEST_BASE_URL: "https://drupal-contributions-drupal9.2.lndo.site/"
        SIMPLETEST_DB: "sqlite://localhost/tmp/db.sqlite"
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://chrome:9515"]'
        LANDO_HOST_IP: "host.docker.internal"
        XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
        # Nightwatch
        DRUPAL_TEST_BASE_URL: 'http://appserver'
        DRUPAL_TEST_DB_URL: 'mysql://drupal9:drupal9@database:3306/drupal9'
        DRUPAL_TEST_WEBDRIVER_HOSTNAME: chrome
        DRUPAL_TEST_WEBDRIVER_PORT: 9515
        DRUPAL_TEST_CHROMEDRIVER_AUTOSTART: 'false'
        DRUPAL_TEST_WEBDRIVER_CHROME_ARGS: "--disable-gpu --headless --no-sandbox"
        DRUPAL_NIGHTWATCH_OUTPUT: reports/nightwatch
        DRUPAL_NIGHTWATCH_IGNORE_DIRECTORIES: node_modules,vendor,.*,sites/*/files,sites/*/private,sites/simpletest

    build:
      - /usr/local/bin/composer global require --dev drupal/coder
      - /usr/local/bin/composer global require dealerdirect/phpcodesniffer-composer-installer
      - /app/vendor/bin/phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer
  chrome:
    type: compose
    app_mount: false
    services:
      image: drupalci/webdriver-chromedriver:production
      command: chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips=

tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush

  si:
    service: appserver
    description: Install Drupal
    cmd:
      - appserver: /app/scripts/site-install.sh

  patch:
    service: appserver
    description: Get a patch from a Drupal project issue queue
    cmd:
      - appserver: php /app/scripts/patch-helpers.php
    options:
      url:
        describe: The url of the patch from the issue queue

  revert:
    service: appserver
    description: Apply a patch from a Drupal project issue queue
    cmd:
      - appserver: php /app/scripts/patch-helpers.php --revert
    patch:
      describe: The name of the patch to revert; i.e. DESCRIPTION-XXXXXXX-YY.patch

  create-patch:
    service: appserver
    description: Creat a patch from your committed changes on your branch.
    cmd:
      - appserver: php /app/scripts/patch-helpers.php --create-patch

  phpunit:
    service: appserver
    user: www-data
    cmd:
      - appserver: php /app/vendor/bin/phpunit -c /app/phpunit.xml

  core-check:
    service: appserver
    cmd:
      - appserver: php /app/scripts/core-check.php

  nightwatch:
    service: appserver
    description: Run Nightwatch.js
    cmd: yarn test:nightwatch
    dir: /app/web/core

  # Custom tools pulled from other projects.
  robo:
    service: appserver
    description: Runs <robo> commmands
    cmd: /app/vendor/bin/robo

  xdebug-on:
    service: appserver
    description: Enable xdebug
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
events:
#  post-destroy:
#    - rm -rfv web
#  pre-rebuild:
#    - rm -rfv web
#    - appserver: php /app/scripts/get-drupal.php
#  post-rebuild:
#    - appserver: /app/scripts/rebuild.sh

`

**Comment by smustgrave** [comment]
Sorry for the bad formatting.  Any help would be appreciated.

**Comment by smustgrave** [comment]
Adding - cd /app/web/core && yarn install to the build as root section resolved this

**Comment by cabagach** [comment]
Thanks for sharing how you got it working, perhaps this issue can be closed?

**Comment by smustgrave** [comment]
Sure

**Comment by cabagach** [comment]
Thanks. And how about #48, did you get it working?
