### ISSUE TITLE
Add support for Drupal 9.

### ISSUE THREAD

**Issue by serundeputy** [thinktandem/drupal-contributions#5]
I think w/ @benjifisher 's improvements we can pass in a branch for the git clone so maybe that is sufficient, but we may need to tweak the `.lando.yml` file as well.

Let's test that out and see if we can make it work for Drupal 8 and 9.

**Comment by danflanagan8** [comment]
Great repo!

Here's what I did to make this install a D9 site.

1. Change `$drupalBranch` to `9.0.x` in `/config/drupal-branch.php`
2. Replace any instance of `drupal8` in the `scripts` directory with `drupal9` (just a find/replace)
3. In `.lando.yml` change the recipe to `drupal9`

I'm not 100% sure that all of that is _required_, but it works!

**Comment by sembrat** [comment]
First, thanks for this helper tool and codebase. It's so helpful to have this stand-up an environment for testing.

Per https://github.com/thinktandem/drupal-contributions/issues/5#issuecomment-665740258 , would there be an opportunity to implement a variable instantiation and replacement of `drupal8` into `config/drupal-branch.php` or within the `rebuild.sh` script?

**Comment by serundeputy** [comment]
@sembrat @danflanagan8 we could make `8.x` and `9.x` branches in this repo w/ the appropos things.

anyone up for a PR?

**Comment by serundeputy** [comment]
maybe a `10.x` branch could be useful too

**Comment by sembrat** [comment]
>anyone up for a PR?

Happy to take a first pass at both.

**Comment by sembrat** [comment]
I suppose we can hold a `10.x` branch for when there's a `drupal10` lando recipe? https://docs.lando.dev/config/drupal9.html#getting-started

**Comment by serundeputy** [comment]
thanks @sembrat and @danflanagan8 !

This work is available on the new `9.x` branch: https://github.com/thinktandem/drupal-contributions/tree/9.x
