### ISSUE TITLE
PHP8 not working properly with Drupal9 recipe

### ISSUE THREAD

**Issue by jacarvajal** [thinktandem/drupal-contributions#68]
Hi!

I've tried to install a new development environment with Drupal 9, so I used the recipe to do so. I realised that the default PHP version is 7.3.29 and decided to upgrade it to PHP8 in the .lando.yml file this way:

`name: d9
recipe: drupal9
config:
  webroot: web
  php: '8.1'
`

And the output is always: "ERROR ==> php version 8.1 is not supported".

I've tested with single/double quotes and no quotes, and also with PHP8.0. Currently I have no way to configure it.

**Comment by gitressa** [comment]
I get PHP 8.1 with this:

`lando init --recipe drupal9 --name drupal9 --source cwd --webroot web php --option php='8.1'`

**_.lando.yml_ content**
```
$ cat .lando.yml 
name: drupal9
recipe: drupal9
config:
  webroot: web
  php: '8.1'
```

**PHP version**
```
$ lando info | grep -A 1 php.ini
    config: { php: '/home/user/.lando/config/drupal9/php.ini' },
    version: '8.1',
```

What is your OS and Lando version?

**Comment by gitressa** [comment]
The above is for testing with a plain vanilla Drupal 9, but if I manually update _/drupal-contributions/.lando.yml_ to this before `lando rebuild -y`, it works equally well:
```
name: drupal-contributions
recipe: drupal9
config:
  webroot: web
  php: '8.1'

[...]
```

**PHP version**
```
~/dev/drupal-contributions$ lando info | grep -A 1 php.ini
    config: { php: '/home/user/.lando/config/drupal9/php.ini' },
    version: '8.1',

```

**Comment by gitressa** [comment]
I get PHP 8.0 with the default installation ...

```
~/dev/drupal-contributions$ lando info | grep -A 1 php.ini
    config: { php: '/home/user/.lando/config/drupal9/php.ini' },
    version: '8.0',
```

**Verifying Lando PHP version**
```
$ lando php -v
PHP 8.0.19 (cli) (built: May 28 2022 09:06:50) ( NTS )

```

**Comment by jacarvajal** [comment]
Oops, my fault, sorry for bothering you.
I realised with your comment that my Lando version was outdated. I thought it was automatically updated with Ubuntu updates, but it wasn't.

My old version was 3.0.14, once I updated to 3.6.5 everything worked perfectly and PHP8.0 was the default version for D9 recipe.

Thank you for your help!

**Comment by gitressa** [comment]
Awesome, I am glad to help and that you got it working!
