### ISSUE TITLE
Provide an option for debugging

### ISSUE THREAD

**Issue by murilohpucci** [thinktandem/drupal-contributions#71]
I've been using the drupal-contributions for a while, and it would be nice the xdebug enabled by default.

**Comment by gitressa** [comment]
It's a great idea to add xdebug support.

But shouldn't it be off by default? From my understanding the performance can be affected by xdebug, and not everyone is using it ...

**Comment by murilohpucci** [comment]
Hey @gitressa, thanks for the answer, and about the performance, you're right xdebug will affect the performance, so I've updated the PR, now by default the xdebug will begin disabled, and if you want to start debugging, you can run `lando xdebug-on`, and after the debug part ends just execute `lando xdebug-off` to disable xdebug.

**Comment by gitressa** [comment]
Thanks for a quick update @murilohpucci, that'll work well. I tried installing and enabling xdebug (though I didn't use it) and Drupal still felt really fast, and pages loaded as normal.

Maybe xdebug performance was more a problem in the past, or perhaps PHPStorm or similar program should also be involved, to really drain the resources? Did you try bench-marking the performance by any chance, and could you see any significant performance hit with or without xdebug enabled?

**Comment by murilohpucci** [comment]
Hey, I haven't tried any benchmark tests, but AFAIK the performance will be affected by the xdebug extension, we're talking about maybe a few seconds of difference, but it exists. So IMO it's a good approach to disable the xdebug by default and allow a tooling command to enable it if the developer wants to. 

FYI: There's a pretty good benchmark comparing both version 2 and 3 of xdebug available at: https://php.watch/articles/xdebug2-vs-3-benchmark.

**Comment by gitressa** [comment]
Thanks for sharing that link, it does look like big improvements between v2 and v3, impressive. But still probably best to keep it off until needed, to save resources, as we both agree.
